### ISSUE TITLE
Add `contains_non_numerical_values` and similar methods to the tables class

### ISSUE THREAD

**Issue by alex-senger** [Safe-DS/Library#351]
### Is your feature request related to a problem?

A method that checks if a table has non_numerical values could be useful.

### Desired solution

The implementation should be fairly simple by using the `remove_columns_with_non_numerical_values` method.

Similar methods should be implemented for
* `contains_duplicate_rows`
* `contains_rows_with_missing_values`
* `contains_rows_with_outliers`

too.

**Comment by lars-reimann** [comment]
We won't work on this. There are already methods to remove rows/columns using these criteria, as well as `Table.summarize_statistics` and various other methods, also on `Column`, to simply check them. Because of this, I don't think these methods are worth adding, particularly since the interface of `Table` is already fairly large.
