### ISSUE TITLE
Buggy Tests

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Library#482]
### Describe the bug

The test: test_should_match_snapshot sometimes runs through and sometimes doesnt. After running the tests a few times, there seems to be no more trouble and just gives warning.

### To Reproduce

1. clone main repo
2. run tests

### Expected behavior

Expect the test to run through

**Comment by lars-reimann** [comment]
Which tests fails specifically? There are multiple tests with that name.

**Comment by Gerhardsa0** [comment]
> Which test fails specifically? There are multiple tests with that name.

this test fails: tests/safeds/data/tabular/containers/_table/test_plot_correlation_heatmap.py

could be something with my setup, I get this Error: This probably means that Tcl wasn't installed properly.

**Comment by lars-reimann** [comment]
It could be related to https://github.com/pypa/virtualenv/issues/93. I've also encountered this when running the tests from the command line sometimes (but never when running the tests using a run configuration in PyCharm). Since the linked issue is now more than 12 years old, I wouldn't get my hopes up that this gets fixed anytime soon. I'm closing this, since there's nothing we can do to fix this besides not using `poetry` anymore.
